// <auto-generated />
using System;
using ChatInbox.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatInbox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InboxDbContext))]
    [Migration("20260925014008_AllowNullOutboundUpdateId")]
    partial class AllowNullOutboundUpdateId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatInbox.Infrastructure.Persistence.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("text")
                        .HasColumnName("last_message_preview");

                    b.Property<long?>("LastTelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_telegram_message_id");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversations_chat");

                    b.HasIndex("LastMessageAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_conversations_activity");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("ChatInbox.Infrastructure.Persistence.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_message_id");

                    b.Property<long?>("TelegramUpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_update_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("TelegramUpdateId")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_update");

                    b.HasIndex("ConversationId", "TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_chat_message");

                    b.HasIndex("ConversationId", "SentAt", "Id")
                        .HasDatabaseName("ix_messages_conversation_time");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ChatInbox.Infrastructure.Persistence.ProcessedUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("update_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("UpdateId")
                        .HasName("pk_processed_updates");

                    b.ToTable("processed_updates", (string)null);
                });

            modelBuilder.Entity("ChatInbox.Infrastructure.Persistence.Message", b =>
                {
                    b.HasOne("ChatInbox.Infrastructure.Persistence.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
